/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package psxtaxi;

import org.mapsforge.core.graphics.GraphicFactory;
import org.mapsforge.core.model.BoundingBox;
import org.mapsforge.core.util.LatLongUtils;
import org.mapsforge.core.util.Parameters;
import org.mapsforge.map.awt.graphics.AwtGraphicFactory;
import org.mapsforge.map.awt.util.AwtUtil;
import org.mapsforge.map.awt.util.JavaPreferences;
import org.mapsforge.map.awt.view.MapView;
import org.mapsforge.map.layer.Layers;
import org.mapsforge.map.layer.cache.TileCache;
import org.mapsforge.map.layer.download.TileDownloadLayer;
import org.mapsforge.map.layer.download.tilesource.OpenStreetMapMapnik;
import org.mapsforge.map.model.Model;
import org.mapsforge.map.model.common.PreferencesFacade;
import psxtaxi.handler.Qh426Handler;
import psxtaxi.handler.Qs121Handler;
import psxtaxi.ui.AirplaneLayer;

import javax.swing.JFrame;
import javax.swing.WindowConstants;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.UUID;
import java.util.prefs.Preferences;

public class App {
    private static final GraphicFactory GRAPHIC_FACTORY = AwtGraphicFactory.INSTANCE;

    public static void main(String[] args) {
        final MapView mapView = new MapView();
        final SimState state = new SimState();
        PsxConnector connector = new PsxConnector("localhost", 10747);
        connector.connect();
        final EventProcessor eventProcessor =
                new EventProcessor(connector,
                        new Qs121Handler(mapView, state)::handle,
                        new Qh426Handler(state)::handle);

        // Square frame buffer
        Parameters.SQUARE_FRAME_BUFFER = true;

        Layers layers = mapView.getLayerManager().getLayers();
        TileDownloadLayer tileDownloadLayer = createMapLayer(mapView, OpenStreetMapMapnik.INSTANCE, 256);
        layers.add(tileDownloadLayer);
        layers.add(new AirplaneLayer(GRAPHIC_FACTORY, mapView.getModel().displayModel, state, 60, true));

        tileDownloadLayer.start();

        mapView.setZoomLevelMin(OpenStreetMapMapnik.INSTANCE.getZoomLevelMin());
        mapView.setZoomLevelMax(OpenStreetMapMapnik.INSTANCE.getZoomLevelMax());

        final PreferencesFacade preferencesFacade = new JavaPreferences(Preferences.userNodeForPackage(App.class));

        JFrame frame = createJFrame(mapView, 1024, 768);

        WindowAdapter windowAdapter = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                eventProcessor.exit();
                mapView.getModel().save(preferencesFacade);
                mapView.destroyAll();
                AwtGraphicFactory.clearResourceMemoryCache();
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            }

            @Override
            public void windowOpened(WindowEvent e) {
                final Model model = mapView.getModel();
                model.init(preferencesFacade);
                eventProcessor.start();
            }
        };
        frame.addWindowListener(windowAdapter);
    }

    private static JFrame createJFrame(MapView mapView, int windowWidth, int windowHeight) {
        final JFrame frame = new JFrame();
        frame.setTitle("PSX Taxi");
        frame.add(mapView);
        frame.pack();
        frame.setSize(windowWidth, windowHeight);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        frame.setVisible(true);
        return frame;
    }

    private static TileDownloadLayer createMapLayer(MapView mapView, OpenStreetMapMapnik tileSource, int tileSize) {
        // Tile cache
        TileCache tileCache = AwtUtil.createTileCache(
                tileSize,
                mapView.getModel().frameBufferModel.getOverdrawFactor(),
                1024,
                new File(System.getProperty("java.io.tmpdir"), UUID.randomUUID().toString()));

        mapView.getModel().displayModel.setFixedTileSize(tileSize);
        tileSource.setUserAgent("psxtaxi-mapsforge-awt");
        return new TileDownloadLayer(tileCache, mapView.getModel().mapViewPosition, tileSource, GRAPHIC_FACTORY);
    }
}
