name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew fatJar
      - name: Release name
        id: release_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Prepare package
        if: startsWith(github.ref, 'refs/tags/')
        run: mv app/build/libs/app-jar-with-dependencies.jar psxtaxi-${{ steps.release_name.outputs.SOURCE_TAG }}-b${{ github.run_number }}.jar
        env:
          SOURCE_TAG: ${{ steps.release_name.outputs.SOURCE_TAG }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SOURCE_TAG: ${{ steps.release_name.outputs.SOURCE_TAG }}
        with:
          files: psxtaxi-${{ steps.release_name.outputs.SOURCE_TAG }}-b${{ github.run_number }}.jar
